# Generated by Django 2.2.3 on 2019-07-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('fields', models.CharField(max_length=200)),
                ('works', models.CharField(max_length=200)),
                ('pictures', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Unknown Author', max_length=30)),
                ('pub_title', models.CharField(max_length=200)),
                ('pub_summary', models.CharField(max_length=200)),
                ('pub_url', models.CharField(max_length=200)),
            ],
        ),
    ]
