# Generated by Django 2.2.3 on 2019-08-02 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='pub_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.Publication'),
        ),
    ]
